apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smartpharmacy-secrets
  namespace: smartpharmacy
spec:
  encryptedData:
    DATABASE_URL: <sealed>
    REDIS_URL: <sealed>
    OCR_LANG: <sealed>
    APP_NAME: <sealed>